# Generated by Django 3.1.5 on 2023-08-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0003_remove_example_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
